UMAP_N_COMPONENTS = 10
UMAP_N_NEIGHBORS = 15
UMAP_MIN_DIST = 0.0
HDBSCAN_MIN_CLUSTER_SIZE = 12
HDBSCAN_MIN_SAMPLES = 5
SAMPLE_CENTRAL_DOCS = 4
SAMPLE_DIVERSE_DOCS = 4
SAMPLE_DOC_SNIPPET_CHARS = 300
TAG_MERGE_AUTO = 0.85  # >= : merge silently
TAG_MERGE_GRAY_LOW = 0.60  # [0.60, 0.85) : LLM adjudicates -> dashboard approval
MULTILABEL_SIMILARITY = 0.60
NOISE_RESCUE_SIMILARITY = 0.50
CONFIDENCE_AUTO_APPLY = 0.70
MAX_TAGS_PER_NOTE = 3
RANDOM_SEED = 42
